### ISSUE TITLE
Request an Optional Value with an Optional Type

### ISSUE THREAD

**Issue by calebkleveter** [skelpo/vapor-request-storage#2]
When you want to access an optional value from the request storage, you pass in the base type of the optional and get an optinal type back. This is not very intuitive. The code to get an optinal should look like this:

```swift
try request.get("key", as: MyType?.self)
```

**Comment by vzsg** [comment]
Pardon the intrusion, but why isn't it intuitive? That's exactly how Swift dictionaries work and I would say that this behavior is just fine. Requesting an optional type explicitly is much more unusual.

**Comment by calebkleveter** [comment]
Hmm, never thought of that 🤔, that is a pretty good point there. I guess because these methods are supposed to act similarly to the dictionary subscripts, that makes prefect sense. The same thing would happen if you assigned a key to `nil`.

Thanks for poking in and explaining that!
